'use strict';
const $=id=>document.getElementById(id);
const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const basename=path=>(path||'').replace(/\\/g,'/').split('/').filter(Boolean).at(-1)||'Projet non identifié';
const short=path=>(path||'').replace(/\\/g,'/').replace(/^.*\/.codex\/worktrees\//,'…/worktrees/');
const age=started=>{if(!started)return 'Inconnu';const s=Math.max(0,Date.now()/1000-started);return s<60?`${Math.floor(s)} s`:s<3600?`${Math.floor(s/60)} min`:s<86400?`${Math.floor(s/3600)} h ${Math.floor(s%3600/60)} min`:`${Math.floor(s/86400)} j`;};
let token='',data=null,view='servers',filtered=[],pending=null,busy=false,refreshBusy=false,lastGood=0;
async function api(path,body){const r=await fetch(path,{method:body?'POST':'GET',headers:{'X-Localdeck-Token':token,...(body?{'Content-Type':'application/json'}:{})},body:body?JSON.stringify(body):undefined});const result=await r.json();if(!r.ok)throw new Error(result.error||`Erreur ${r.status}`);return result;}
function toast(message){$('toast').textContent=message;$('toast').hidden=false;setTimeout(()=>$('toast').hidden=true,6500);}
function badge(agent){return `<span class="badge ${agent==='Inconnu'?'neutral':''}">${esc(agent)}</span>`;}
function render(){
 if(!data)return;
 $('hostname').textContent=data.hostname||'PC Windows';
 $('server-count').textContent=data.servers.length;$('docker-count').textContent=data.containers.length;$('tree-count').textContent=data.worktrees.length;
 const labels={servers:['Serveurs locaux',"Retrouvez ce qui tourne, d'où ça vient et qui s'y connecte.",'Processus en écoute'],containers:['Conteneurs Docker','Conteneurs actifs et arrêtés, ports publiés et projets Compose.','Conteneurs sur ce PC'],worktrees:['Worktrees Git','Retrouvez aussi les copies de travail sans serveur actif.','Copies de travail détectées']};
 const [title,subtitle,list]=labels[view];$('title').textContent=title;$('subtitle').textContent=subtitle;$('list-title').textContent=list;$('crumb').textContent=view==='servers'?'Serveurs':view==='containers'?'Docker':'Worktrees';
 $('system-control').hidden=view!=='servers';$('agent').parentElement.hidden=view==='containers';
 if($('agent').dataset.view!==view){const values=view==='worktrees'?['Codex','Git']:['Codex','OpenCode','Inconnu'];$('agent').innerHTML='<option value="all">Toutes</option>'+values.map(v=>`<option>${v}</option>`).join('');$('agent').dataset.view=view;$('agent').previousSibling.textContent=view==='worktrees'?'Type':'Origine';}
 const q=$('search').value.toLowerCase(),filter=$('agent').value;
 filtered=data[view].filter(row=>{
  if(view==='servers'&&!$('system').checked&&!row.stoppable&&!row.repo&&row.agent==='Inconnu'&&!row.containers?.length)return false;
  if(view==='servers'&&filter!=='all'&&row.agent!==filter)return false;
  if(view==='worktrees'&&filter!=='all'&&row.kind!==filter)return false;
  return JSON.stringify(row).toLowerCase().includes(q);
 });
 $('visible-count').textContent=`${filtered.length} affichés · ${data[view].length} détectés`;
 const columns=view==='servers'?['Port / protocole','Projet / processus','Origine','Utilisation','Depuis','Actions']:view==='containers'?['Conteneur / image','Projet Compose','Ports publiés','État','Actions']:['Projet / worktree','Branche','Type','Serveurs','État'];
 $('thead').innerHTML='<tr>'+columns.map(c=>`<th scope="col">${c}</th>`).join('')+'</tr>';
 $('tbody').innerHTML=filtered.map((r,i)=>{
  if(view==='servers'){
   const location=r.repo||r.cwd;const title=r.repo?basename(r.repo):r.name;
   return `<tr><td>${r.protocol==='TCP'?`<a class="port" href="http://localhost:${r.port}" target="_blank" rel="noopener noreferrer" title="Essayer ce port dans le navigateur">:${r.port}</a>`:`<span class="port">:${r.port}</span>`}<span class="sub">${esc(r.protocol)} · PID ${r.pid}</span></td><td class="project">${esc(title)}<span class="sub" title="${esc(location)}">${esc(location?short(location):'Dossier inaccessible')}</span></td><td>${badge(r.agent)}${r.repo?.includes('/.codex/')||r.repo?.includes('\\.codex\\')?'<span class="sub">Worktree Codex</span>':''}${r.containers?.length?`<span class="sub">Docker · ${esc(r.containers.join(', '))}</span>`:''}</td><td class="usage">${r.connections} connexion${r.connections!==1?'s':''}<span class="sub">${(r.memory/1048576).toFixed(0)} Mo · ${r.cpu.toFixed(1)} % CPU</span></td><td class="usage">${age(r.started)}</td><td><div class="row-actions"><button class="small" data-detail="${i}">Détails</button>${r.stoppable?`<button class="small stop" data-stop="${i}">Arrêter</button>`:'<span class="protected">Protégé</span>'}</div></td></tr>`;
  }
  if(view==='containers')return `<tr><td class="project">${esc(r.name)}<span class="sub" title="${esc(r.image)}">${esc(r.image)}</span></td><td>${esc(r.project||'Hors Compose')}<span class="sub">${esc(r.service||'')}</span></td><td class="path">${r.ports.map(p=>`${esc(p.host_ip)}:${esc(p.host_port)} → ${esc(p.container_port)}`).join('<br>')||'Non publié'}</td><td><span class="badge ${r.state==='running'?'':'neutral'}">${esc(r.state==='running'?'En cours':r.state)}</span>${r.health?`<span class="sub">${esc(r.health)}</span>`:''}</td><td><div class="row-actions"><button class="small" data-detail="${i}">Détails</button>${r.stoppable?`<button class="small stop" data-stop="${i}">Arrêter</button>`:'<span class="protected">'+(r.state==='running'?'Protégé':'Arrêté')+'</span>'}</div></td></tr>`;
  return `<tr><td class="project worktree-path">${esc(basename(r.repo))}<span class="sub worktree-path" title="${esc(r.path)}">${esc(short(r.path))}</span></td><td class="path">${esc(r.branch)}</td><td>${badge(r.kind)}</td><td>${r.servers?`<span class="running"><span class="led"></span>${r.servers} port${r.servers!==1?'s':''}</span>`:'Aucun serveur'}</td><td><span class="badge ${r.exists?'neutral':'amber'}">${r.exists?'Présent':'Dossier absent'}</span>${r.locked?'<span class="sub">Verrouillé</span>':''}</td></tr>`;
 }).join('');
 $('empty').hidden=filtered.length>0;$('empty').textContent=data.loading?'Premier inventaire en cours…':q?'Aucun résultat pour cette recherche.':view==='servers'?"Aucun serveur de développement identifié. Activez « Inclure les services système » pour voir tous les ports.":view==='containers'?'Aucun conteneur détecté. Vérifiez Docker Desktop.':'Aucun worktree trouvé dans les dossiers configurés.';
 $('updated').textContent=data.timestamp?`Scan à ${new Date(data.timestamp*1000).toLocaleTimeString('fr-FR')} · ${(data.scan_ms/1000).toFixed(1)} s`:'Premier scan en cours…';
 $('warnings').innerHTML=(data.warnings||[]).map(w=>`<div class="notice">${esc(w)}</div>`).join('');
 $('explanation').textContent=view==='servers'?"L'origine indique un ancêtre Codex ou OpenCode retrouvé. Les connexions montrent les clients actifs à l'instant du scan. Aucune connexion ne signifie pas que le serveur est inutile.":view==='worktrees'?"Git recense les worktrees des repos découverts. Les dossiers Codex sont inclus. Ajoutez d'autres racines dans config.json, puis relancez le collecteur.":"L'arrêt vise le conteneur sélectionné. Les volumes et les images sont conservés. Localdeck protège son propre conteneur.";
}
async function refresh(){if(refreshBusy)return;refreshBusy=true;$('refresh').disabled=true;try{if(!token)token=(await api('/api/session')).token;data=await api('/api/snapshot');lastGood=Date.now();render();$('connection').classList.remove('stale');$('connection').innerHTML='<span class="led"></span>'+ (data.loading?'Premier scan…':'Collecteur connecté');}catch(e){$('connection').classList.add('stale');$('connection').innerHTML='<span class="led"></span>Collecteur indisponible';$('warnings').innerHTML=`<div class="notice">${esc(e.message)}${lastGood?' Dernier inventaire conservé, données anciennes.':''}</div>`;if(!data){$('empty').hidden=false;$('empty').textContent='Démarrez le collecteur avec Start-Localdeck.ps1, puis actualisez.';}}finally{refreshBusy=false;$('refresh').disabled=false;}}
function details(r){
 $('detail-title').textContent=view==='servers'?`${r.name} · :${r.port}`:r.name;
 if(view==='containers')$('detail-content').innerHTML=`<dl><dt>Image</dt><dd>${esc(r.image)}</dd><dt>Conteneur</dt><dd class="path">${esc(r.id)}</dd><dt>Projet</dt><dd>${esc(r.project||'Inconnu')}</dd><dt>Service</dt><dd>${esc(r.service||'Inconnu')}</dd><dt>Dossier</dt><dd class="path">${esc(r.directory||'Label Compose absent')}</dd><dt>Démarré</dt><dd>${esc(r.started)}</dd></dl>`;
 else $('detail-content').innerHTML=`${badge(r.agent)}<p>${esc(r.evidence)}</p><dl><dt>PID</dt><dd>${r.pid}</dd><dt>Projet Git</dt><dd class="path">${esc(r.repo||'Non identifié')}</dd><dt>Dossier réel</dt><dd class="path">${esc(r.cwd||'Inaccessible')}</dd><dt>Écoute</dt><dd class="path">${r.bindings.map(esc).join(', ')} · ${esc(r.protocol)}</dd><dt>Démarré</dt><dd>${r.started?new Date(r.started*1000).toLocaleString('fr-FR'):'Inconnu'}</dd></dl><h3>Clients locaux actuellement connectés</h3>${r.clients.length?r.clients.map(c=>`<div class="ancestor">${esc(c.name||'Inconnu')} <span class="sub">PID ${c.pid} · ${esc(c.endpoint)}</span></div>`).join(''):'<p>Aucun client local trouvé à cet instant.</p>'}<h3>Processus et chaîne des parents</h3>${r.ancestry.map(p=>`<div class="ancestor"><strong>${esc(p.name)}</strong> <span class="tag">PID ${p.pid}</span><span class="sub path">${esc(p.cwd||'Dossier inaccessible')}</span><pre>${esc(p.command||'Commande inaccessible')}</pre></div>`).join('')}`;
 $('details').showModal();
}
function requestStop(r){if(busy)return;pending=view==='containers'?{kind:'container',id:r.id,started:r.started}:{kind:'process',pid:r.pid,started:r.started};$('confirm-description').textContent=view==='containers'?`Le conteneur « ${r.name} » sera arrêté. Ses volumes seront conservés.`:`Le processus ${r.name}, PID ${r.pid}, sera terminé. Tous ses ports seront fermés, dont ${r.port}. Un superviseur peut le relancer.`;$('confirm').showModal();}
document.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>{view=b.dataset.view;document.querySelectorAll('[data-view]').forEach(n=>n.classList.toggle('active',n===b));$('search').value='';$('agent').value='all';render();}));
$('tbody').addEventListener('click',e=>{const detail=e.target.closest('[data-detail]'),stop=e.target.closest('[data-stop]');if(detail)details(filtered[+detail.dataset.detail]);if(stop)requestStop(filtered[+stop.dataset.stop]);});
for(const id of ['search','system','agent'])$(id).addEventListener('input',render);
$('refresh').addEventListener('click',refresh);$('close-details').addEventListener('click',()=>$('details').close());$('cancel-stop').addEventListener('click',()=>$('confirm').close());
$('confirm-stop').addEventListener('click',async()=>{if(!pending||busy)return;busy=true;$('confirm-stop').disabled=true;$('confirm-stop').textContent='Arrêt en cours…';try{const result=await api('/api/stop',pending);$('confirm').close();toast(result.message);await refresh();setTimeout(refresh,10000);}catch(e){$('confirm').close();toast(e.message);}finally{busy=false;pending=null;$('confirm-stop').disabled=false;$('confirm-stop').textContent='Arrêter';}});
refresh();setInterval(refresh,8000);
